### ISSUE TITLE
cannot install on 4.03

### ISSUE THREAD

**Issue by ygrek** [mfp/extprot#19]
due to 
```
$ opam sw show
4.03.0
$ opam install extprot
The following dependencies couldn't be met:
  - extprot -> sexplib < 113.01.00
Your request can't be satisfied:
  - sexplib<113.01.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".

No solution found, exiting
```

constrain on sexplib is representing the version when it dropped camlp4 syntax extension

**Comment by mfp** [comment]
OK, I'm looking into this as I prepare the 1.3.0 release.

**Comment by mfp** [comment]
@ygrek Do you care about compatibility with 4.01 and lower? I myself am OK with >= 4.02.3, and I'm not exactly looking forward to adding a few hundred lines of boilerplate code to pretty-print internal structures for debugging.code generation.

I could:

1. drop the `--debug-reduced` and `--debug-concrete` options
2. switch to sexplibs's ppx (will thus need 4.02, likely 4.02.3 transitively if sexplib uses Ppx_core)
3. switch to something like ppx_deriving (also >= 4.02)
4. hand-write pretty-printers (ugh)

In fact I don't remember the last time I actually used `--debug-reduced/concrete` (since I haven't messed with code generation in ages), so I'm probably doing (1).

**Comment by ygrek** [comment]
I am personally ok with 4.02+ constrain, and I didn't use `debug` options either - debugged by looking at final output - which I admit is not very hi-tech :)

**Comment by mfp** [comment]
I just removed the flags since it wasn't clear they'll be needed anytime soon, and dropping dependencies is always a good thing. Awaiting merge into OPAM repos of 1.3.0: https://github.com/ocaml/opam-repository/pull/7311

**Comment by mfp** [comment]
Incidentally, the tests run 10% faster on 4.03 vs 4.02.3 (both with an without flambda, the latter being maybe a tiny bit faster, at most 1% -- the read/write code is already inlined by the code generator so little if any change is expected).

**Comment by ygrek** [comment]
Thanks, and 10% speedup for free is awesome.
PS master not pushed
