### ISSUE TITLE
new tag for release please

### ISSUE THREAD

**Issue by ygrek** [mfp/extprot#32]
I can make release to opam no problem

**Comment by mfp** [comment]
On Mon, Oct 15, 2018 at 11:03:52AM +0000, ygrek wrote:
> I can make release to opam no problem

Just released 1.6.0. I was going to do the OPAM PR as well, but I've just
realized that in the meantime OPAM 2.0 has been released and the repository
format updated, so have to read up a bit to see if there's any significant
change to the repository and manual release process (I'm not super fond
of opam-publish because sometimes I get the feeling I don't really know what
it's doing).

-- 
Mauricio Fernández

**Comment by ygrek** [comment]
Previous versions were autoconverted to 2.0 so it is usual copy of previous version and update to 1.6.0 to release - that's how I do releases manually most of the time :)
https://github.com/ocaml/opam-repository/pull/12813
